### PR TITLE
New business copy

### PR DESCRIPTION
**Pull request by sofer**

### CODE REVIEW

**Comment by iteles** [comment]
@sofer Might this not be a little easier to follow if it was all in one file you could scroll through, with a contents table/guide at the top (exactly like the one you already have but using anchor points on the file rather than individual files)? :blush:

**Comment by sofer** [comment]
@iteles arguably it depends on how you are navigating it. If as a README on Github, then definitely as a single file, but if in a Gitbook, the flow is slightly different.

**Comment by iteles** [comment]
:+1: Fair point. Is this ready for a review and merge?

**Comment by sofer** [comment]
@iteles yes, please.

**Pull request merged**
