### PR TITLE
Linkedin two

### PR DESCRIPTION
**Pull request by hdrdavies**
Responding to comments here: 

https://github.com/FAC6/book/pull/122#issuecomment-149594203

### CODE REVIEW

**Comment by sofer** [comment]
@hdrdavies I liked the first draft, but this is even better. @iteles?

**Comment by iteles** [comment]
Looks good!

Merging this in so FAC6 can start using it and opening issues against it :+1: We'll then tweak before we add to the playbook.

Thought the tip you used to have in here about not using your main email address but rather a new one that forwards to your existing email address (for example) was useful though.

@hdrdavies Curious to know why you didn't add the changes as a commit to your previous PR and chose to create a new one?

**Comment by hdrdavies** [comment]
...because I didn't realise that was the done thing. Still a Github noob! :tired_face:

**Comment by iteles** [comment]
Ha, don't worry, it's not a _big_ thing, just easier to track :blush: :+1:

**Pull request merged**
