### PR TITLE
add faq repo link

### PR DESCRIPTION
**Pull request by hdrdavies**
-After discussion during S-G-C Friday 30th Oct

### CODE REVIEW

**Comment by iteles** [comment]
@hdrdavies Did you create a whole new organisation rather than a new repo in an existing FAC organisation?

**Comment by hdrdavies** [comment]
I did, but I can make a repo on foundersandcoders instead if you would prefer @iteles

**Comment by iteles** [comment]
@hdrdavies Think that would be less likely to get 'lost' given the amount of organisations we're a part of already :blush:

**Comment by sofer** [comment]
@hdrdavies @iteles https://github.com/fac6 is probably a good home for a fac6faq

**Comment by hdrdavies** [comment]
@sofer I have a feeling it could be relevant for subsequent facs?

**Comment by iteles** [comment]
@hdrdavies :+1: I agree. But we could keep it in FAC6 for now so it's easy access for you guys and we'll move it into the main F&C repo when FAC7 start.

**Comment by hdrdavies** [comment]
@iteles @sofer  ok cool - I've created it here

https://github.com/FAC6/facfaq

Is there a good place to pin it?

**Comment by iteles** [comment]
@hdrdavies I would add it to the fac6 book readme! (In the interest of keeping things as accessible as possible, I don't know how much you guys actually use the gitbook version of the repo)

**Comment by hdrdavies** [comment]
@iteles @sofer  Ok cool - added in this PR 

https://github.com/FAC6/book/pull/136

**Pull request closed without merging**
