### PR TITLE
gitcommandREADME extra issues command resolves #22

### LINKED ISSUE #22: Who shuts down issues?
Are issues shut down automatically? Are they shut down after pull requests are merged?

What is the best protocol for closing issues?

### PR DESCRIPTION
**Pull request by thegsi**

### CODE REVIEW

**Comment by thegsi** [comment]
Should close issue 22 automatically.

**Comment by iteles** [comment]
@thegsi Have you taken a look at how this looks in the markdown preview?

screen shot 2015-09-28 at 09 28 46

I think some of those are meant to be **titles** or `code blocks` :blush:

**Comment by thegsi** [comment]
Yes, sorry, Monday morning! Will fix.

**Comment by thegsi** [comment]
Looking intp this, I totally agree about the titles and formatting in general was sloppy on my part. However should the other information be marked as code? 'Resolves, close' etc. These terms/commands will be in commit messages or pull request messages? Are these commands?

**Comment by iteles** [comment]
@thegsi Really it's whatever you think makes it clearer!

**Pull request closed without merging**
